### ISSUE TITLE
Tutorials 4, 5, and 2

### ISSUE THREAD

**Issue by luizfelippesr** [IMAGINE-Consortium/imagine#22]
There are 3 tutorials which still need to be updated:
* [x] Tutorial 4, which demonstrates the use of Masks with Hammurabi
    * ~better masks integration with Hammurabi needs to be implemented~ (became #26)
* [x] Tutorial 5, which illustrates the use of the pipeline  with Hammurabi
* ~Tutorial 2, which illustrates MPI parallelisation~

**Comment by luizfelippesr** [comment]
6c62b117f4164dbaeed6e152371814221fc7508b

**Comment by luizfelippesr** [comment]
Steps while sorting out tutorial 4:
* b3df3aff - Finishes correcting tutorial_four, which is now called tutorial_masks
* 2eefef81- Includes the tutorial_masks in the docs.

**Comment by 1313e** [comment]
Tutorial 2 will need to have its imports fixed.
Remember that you should ideally always import from subpackages, not from submodules (the latter is done by `__init__` dunder files).
So,
```python
from imagine.observables import ObservableDict
```
instead of
```python
from imagine.observables.observable_dict import ObservableDict
```

I did write the imports in the `imagine.fields.hamx` subpackage such that the contents of the submodules are available at it (as they should be), but I guess that importing from the submodule instead (so, `from imagine.fields.hamx.breg_lsa import BregLSA` instead of `from imagine.fields.hamx import BregLSA`) can add some clarity.
Both imports will work just fine.

**Comment by luizfelippesr** [comment]
I am removing the task of correcting tutorial 2. Originally, tutorial 2 was illustrating a more time consuming task in IMAGINE 1.x (i.e. before the restructure). Later, the same tutorial was used to illustrate the MPI parellesation of the code using ipyparallel. 

I do not think this tutorial is useful any more. In the present, MPI is used to distribute tasks to different nodes in a cluster, and Simulators (e.g. Hammurabi) and Fields are supposed to be already parallelised with OpenMP (or similar). While running on a single machine with a jupyter notebook, it is probably better *not* to use MPI.
